/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/av2gWuYwomZ
 */
import Link from "next/link";

export function Header() {
  return (
    <header className="w-full py-4 md:py-4">
      <div className="container flex items-center justify-between px-4 md:px-6">
        <div className="flex items-center space-x-4">
          <Link className="flex items-center space-x-2" href="#">
            {/* <FlagIcon className="w-12 h-12" /> */}
            <img src="/logo.png" alt="Logo" className="w-12 h-12" />
            <span className="text-2xl font-bold tracking-tighter">Revu</span>
          </Link>
        </div>
        <nav className="hidden md:flex items-center space-x-4"></nav>
      </div>
    </header>
  );
}

function FlagIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/s=vg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  );
}
