/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/av2gWuYwomZ
 */
import Link from "next/link";

export function Header() {
  return (
    <header className="w-full py-4 md:py-4">
      <div className="container flex items-center justify-between px-4 md:px-6">
        <div className="flex items-center space-x-4">
          <Link className="flex items-center space-x-2" href="#">
            {/* <FlagIcon className="w-12 h-12" /> */}
            <img
              src="/Revu-Landing-Page
/logo.png"
              alt="Logo"
              className="w-12 h-12"
            />
            <span className="text-2xl font-bold tracking-tighter">Revu</span>
          </Link>
        </div>
        <nav className="hidden md:flex items-center space-x-4"></nav>
      </div>
    </header>
  );
}
